# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cSrC7VR6ps4tsyzjXsj2Wof2db6wCpQA
"""

print("get lost")